[package]
name = "spinoso-regexp"
version = "0.3.0"
authors = ["Ryan Lopopolo <rjl@hyperbo.la>"]
edition = "2021"
rust-version = "1.62.0"
description = """
Regex implementation for Ruby Regexp core type in Artichoke Ruby
"""
repository = "https://github.com/artichoke/artichoke"
readme = "README.md"
license = "MIT"
keywords = ["artichoke", "onig", "regex", "regexp", "ruby"]
categories = ["data-structures", "parser-implementations"]

[dependencies]
bitflags = "1.3.0"
bstr = { version = "0.2.9", default-features = false }
onig = { version = "6.3.0", optional = true, default-features = false }
# Ensure the `regex` minimum version is at least 1.5.5 to pull in a fix for a
# DoS vulnerability.
#
# See: CVE-2022-24713
# https://github.com/artichoke/artichoke/pull/1729
regex = { version = "1.5.5", default-features = false, features = ["std", "unicode-perl"] }
scolapasta-string-escape = { version = "0.3.0", path = "../scolapasta-string-escape", default-features = false }

[features]
default = ["oniguruma", "regex-full"]
oniguruma = ["dep:onig"]
regex-full = ["regex-perf", "regex-unicode"]
regex-perf = ["regex/perf"]
regex-unicode = ["regex/unicode"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
