[package]
name = "spinoso-securerandom"
version = "0.2.0"
authors = ["Ryan Lopopolo <rjl@hyperbo.la>"]
edition = "2021"
rust-version = "1.62.0"
description = """
Secure PRNG backend for Artichoke Ruby, implements 'securerandom' package
"""
repository = "https://github.com/artichoke/artichoke"
readme = "README.md"
license = "MIT"
keywords = ["artichoke", "rand", "random", "rng", "spinoso"]
categories = ["algorithms"]

[dependencies]
base64 = { version = "0.13.0", default-features = false, features = ["alloc"] }
rand = "0.8.0"
scolapasta-hex = { version = "0.2.0", path = "../scolapasta-hex", default-features = false, features = ["alloc"] }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
