[package]
name = "spinoso-time"
version = "0.5.0"
authors = ["Ryan Lopopolo <rjl@hyperbo.la>"]
edition = "2021"
rust-version = "1.62.0"
description = """
Datetime handling for Artichoke Ruby
"""
repository = "https://github.com/artichoke/artichoke"
readme = "README.md"
license = "MIT"
keywords = ["artichoke", "date", "datetime", "spinoso", "time"]
categories = ["date-and-time"]

[features]
default = ["chrono", "tzrs", "tzrs-local"]
chrono = ["dep:chrono", "dep:chrono-tz"]
tzrs = ["dep:once_cell", "dep:regex", "dep:tz-rs", "dep:tzdb"]
tzrs-local = ["tzrs", "tzdb?/local"]

[dependencies]
chrono = { version = "0.4.19", default-features = false, features = ["clock"], optional = true }
chrono-tz = { version = "0.6.0", default-features = false, optional = true }
once_cell = { version = "1.12.0", optional = true }
regex =  { version = "1.5.5", default-features = false, features = ["std", "unicode-perl"], optional = true }
tz-rs = { version = "0.6.10", default-features = false, optional = true }
tzdb = { version = "0.2.4", default-features = false, optional = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
