[package]
name = "spinoso-random"
version = "0.3.0"
authors = ["Ryan Lopopolo <rjl@hyperbo.la>"]
edition = "2021"
rust-version = "1.62.0"
description = """
Implementation of Ruby Random Core class.
"""
repository = "https://github.com/artichoke/artichoke"
readme = "README.md"
license = "MIT"
keywords = ["random", "rand", "rng", "mt", "spinoso"]
categories = ["algorithms", "no-std"]

[dependencies]
getrandom = { version = "0.2.0", default-features = false }
libm = "0.2.2"
rand = { version = "0.8.0", optional = true, default-features = false }
# 0.6.1 is vulnerable to underfilling a buffer.
#
# https://rustsec.org/advisories/RUSTSEC-2021-0023
rand_core = { version = "0.6.2", optional = true, default-features = false }
rand_mt = { version = "4.1.0", default-features = false }

[features]
default = ["random-rand", "rand-traits", "std"]
# Enables range sampling methods for the `rand()` function.
random-rand = ["rand", "rand-traits"]
# Enables implementations of `RngCore` on `Random` and `Mt` types.
rand-traits = ["rand_core"]
std = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
