[package]
name = "spinoso-math"
version = "0.3.0"
authors = ["Ryan Lopopolo <rjl@hyperbo.la>"]
edition = "2021"
rust-version = "1.62.0"
description = """
Implementation of the Ruby Math module
"""
repository = "https://github.com/artichoke/artichoke"
readme = "README.md"
license = "MIT"
keywords = ["libm", "math", "no_std", "spinoso"]
categories = ["algorithms", "no-std"]

[dependencies]
libm = { version = "0.2.2", optional = true }

[features]
default = ["full"]
# Implement the full Ruby `Math` API by including external crates for missing
# `std` APIs.
full = ["dep:libm"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
