[package]
name = "spec-runner"
version = "0.6.0"
authors = ["Ryan Lopopolo <rjl@hyperbo.la>"]
edition = "2021"
rust-version = "1.62.0"
description = "Binary for running Ruby Specs with Artichoke Ruby"
repository = "https://github.com/artichoke/artichoke"
readme = "README.md"
license = "MIT"
keywords = ["artichoke", "artichoke-ruby", "ruby", "ruby-spec", "testing"]
categories = ["development-tools::testing"]

[dependencies]
artichoke = { version = "0.1.0-pre.0", path = "..", default-features = false, features = ["backtrace", "kitchen-sink"] }
clap = { version = "3.2.5", default-features = false, features = ["std", "suggestions"] }
rust-embed = "6.3.0"
serde = { version = "1.0.136", features = ["derive"] }
termcolor = "1.1.0"
toml = { version = "0.5.8", default-features = false }

[dev-dependencies]
bstr = { version = "0.2.9", default-features = false }

# `spec-runner` is a regression testing tool
# Remove it from the main artichoke workspace.
[workspace]
members = ["."]

[profile.release]
debug = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
